title: Your awesome title
theme: minima
author: Justin Li
email: jli2@ebnet.org
description: > As of 2022, I am a Sophomore Picture:

Social Media: (I don't really use social media so...) Discord: Nedhelp#2715

Brag Sheet: First degree black belt at Taekwondo (6th grade). Got past 6th Grade ABRSM on the Saxophone. A 4.0+ GPA. Skipped Geo-Trig over the Summer. 
# social links
github_username:  justinli0

show_excerpts: true # set to false to remove excerpts on the homepage
